import React, { useEffect } from 'react';
import { Link } from 'react-router-dom';

function PrivacyPolicy() {
  useEffect(() => {
    window.scrollTo(0, 0);
    if (window.AOS) {
      window.AOS.init();
    }
  }, []);

  return (
    <>
      <style>{`
        .legal-banner {
          background-image: url(/myimg/vigil_legal_banner_v2.png) !important;
          background-size: cover !important;
          background-position: center !important;
          background-repeat: no-repeat !important;
        }
        @media (max-width: 991px) {
          #scroll-btn {
            display: flex !important;
            justify-content: center !important;
            margin-bottom: 30px !important;
          }
          .nav-menu {
            display: flex !important;
            flex-direction: column !important;
            align-items: center !important;
            justify-content: center !important;
            padding: 0 !important;
            margin: 0 auto !important;
            width: 100% !important;
            max-width: 320px !important;
          }
          .scroll-btn .nav-menu li {
            width: 100% !important;
            display: flex !important;
            justify-content: center !important;
            margin: 0 0 10px 0 !important;
            float: none !important;
          }
          .scroll-btn .nav-menu li a,
          .luminix-default-btn.pill.faq-btn {
            width: 100% !important;
            display: inline-flex !important;
            justify-content: center !important;
            align-items: center !important;
            text-align: center !important;
          }
        }
      `}</style>

      <div className="breadcrumb-wrapper legal-banner">
        <div className="container">
          <div className="breadcrumb-content">
            <h1 className="breadcrumb-title">Privacy Policy</h1>
            <div className="breadcrumb-menu-wrapper">
              <div className="breadcrumb-menu-wrap">
                <div className="breadcrumb-menu">
                  <ul>
                    <li><Link to="/">Home</Link></li>
                    <li><img src="/assets/images/breadcrumb/right-arrow.svg" alt="right-arrow" /></li>
                    <li aria-current="page">Privacy Policy</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div className="luminix-padding-section">
        <div className="container">
          <div className="row">
            <div className="col-lg-3">
              <nav id="scroll-btn" className="scroll-btn" data-aos="fade-up" data-aos-duration="700">
                <ul className="nav-menu">
                  <li>
                    <Link to="/terms-conditions" className="luminix-default-btn pill faq-btn">Terms & Conditions
                      <svg width="19" height="16" viewBox="0 0 19 16" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path d="M11.2139 1.5L17.7139 8M17.7139 8L11.2139 14.5M17.7139 8L0.999581 8" stroke="#000" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round"></path>
                        <path d="M11.2139 1.5L17.7139 8M17.7139 8L11.2139 14.5M17.7139 8L0.999581 8" stroke="#000" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round"></path>
                      </svg>
                    </Link>
                  </li>
                  <li>
                    <Link to="/privacy-policy" className="luminix-default-btn pill faq-btn active">Privacy Policy
                      <svg width="19" height="16" viewBox="0 0 19 16" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path d="M11.2139 1.5L17.7139 8M17.7139 8L11.2139 14.5M17.7139 8L0.999581 8" stroke="#000" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round"></path>
                        <path d="M11.2139 1.5L17.7139 8M17.7139 8L11.2139 14.5M17.7139 8L0.999581 8" stroke="#000" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round"></path>
                      </svg>
                    </Link>
                  </li>
                </ul>
              </nav>
            </div>
            <div className="col-lg-9">
              <section id="about" className="section">
                <div className="luminix-term-condition-content">
                  <p className="title-text">This Privacy Policy explains how Vigil collects, uses, and protects your personal information and your child's data. We are committed to the highest global standards of data privacy and child safety.</p>
                  <h3>What We Collect:</h3>
                  <p>We collect the information you provide at signup (name, email, billing info) and the monitoring data generated by your child's device (app usage, websites visited, location, screen activity). All data is encrypted in transit and at rest using AES-256 encryption.</p>
                </div>
                <div className="luminix-term-condition-content">
                  <h3>How We Use Your Data:</h3>
                  <p>Your data is used solely to provide, improve, and support the Vigil service. We never sell, rent, or share your personal information or your child's data with third-party advertisers. We may share anonymized, aggregated statistics to improve online child safety research.</p>
                </div>
                <div className="luminix-term-condition-content">
                  <h3>Data Retention:</h3>
                  <p>Activity logs and location history are retained for the duration of your subscription as specified by your plan (7 days, 30 days, or unlimited, depending on your tier). Upon account cancellation, all personal data is deleted within 30 days.</p>
                </div>
                <div className="luminix-term-condition-content">
                  <h3>Your Privacy Rights:</h3>
                  <p>Regardless of your location, you have the right to request access to the personal data we hold about you, request deletion of that data, and opt out of any future data usage. We do not sell your personal data to third parties. To exercise these rights, contact us at support@vigil-1.com.</p>
                </div>
                <div className="luminix-term-condition-content">
                  <h3>Security:</h3>
                  <p>Vigil employs industry-leading security practices including end-to-end encryption, two-factor authentication, regular third-party security audits, and secure, distributed data centers. In the unlikely event of a data breach, we will notify affected users within 72 hours as required by applicable data protection laws.</p>
                </div>
                <div className="luminix-term-condition-content">
                  <h3>Contact Our Privacy Team:</h3>
                  <p>For any privacy-related questions or requests, please contact us at support@vigil-1.com or through our global support center as listed on our Contact page.</p>
                </div>
              </section>
            </div>
          </div>
        </div>
      </div>

    </>
  );
}

export default PrivacyPolicy;
